availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

steps:
  # get gcp info with debug
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo ">> GITHUB_TOKEN length: ${#GITHUB_TOKEN}"
        git config --global url."https://oauth2:$$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
        echo ">> Git config set:"
        git config --global -l
        echo ">> Starting submodule clone"
        git submodule update --init --recursive
    secretEnv: ['GITHUB_TOKEN']
  # build docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/repointerviewer/backend:$SHORT_SHA',
      './backend'
    ]
  # push docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/repointerviewer/backend:$SHORT_SHA'
    ]
  # make release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        export PROJECT_ID=repointerviewer
        IMAGE_PATH=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/repointerviewer/backend

        DIGEST=$(gcloud artifacts docker images describe asia-northeast1-docker.pkg.dev/${PROJECT_ID}/repointerviewer/backend:$SHORT_SHA \
          --format="value(image_summary.digest)")

        if [ "$BRANCH_NAME" = "develop" ]; then
          PIPELINE_NAME="repointerviewer-pipeline-stg"
        elif [ "$BRANCH_NAME" = "main" ]; then
          PIPELINE_NAME="repointerviewer-pipeline-prod"
        else
          echo "Branch $BRANCH_NAME is not a deployable branch."
          exit 0
        fi

        gcloud deploy releases create release-$(date +%s) \
          --delivery-pipeline=$PIPELINE_NAME \
          --region=asia-northeast1 \
          --project=${PROJECT_ID} \
          --source=.gcp_infra \
          --skaffold-file=skaffold.yaml \
          --images=backend=asia-northeast1-docker.pkg.dev/${PROJECT_ID}/repointerviewer/backend@$DIGEST
          
options:
  logging: CLOUD_LOGGING_ONLY
