apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: repointerviewer-pipeline
serialPipeline:
  stages:
    - targetId: backend-stg
      profiles: [staging]
    - targetId: backend-prod
      profiles: [production]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-stg
run:
  location: projects/repointerviewer/locations/asia-northeast1
  service: backend-stg

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: backend-prod
run:
  location: projects/repointerviewer/locations/asia-northeast1
  service: backend-prod
