# trigger by github 
# docker build & push artifact registry
# cloudbuild.yaml
steps:
  # Build & Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/repointerviewer/backend',
      './backend'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/repointerviewer/backend'
    ]

  # Release via Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        export GOOGLE_API_KEY=$(gcloud secrets versions access latest --secret="google-api-key")
        export MODEL_NAME=$(gcloud secrets versions access latest --secret="model-name")
        export REDIS_HOST=$(gcloud secrets versions access latest --secret="redis-host")

        # Set envs for skaffold.yaml through substitutions or via profiles (recommended)
        gcloud deploy releases create release-$(date +%s) \
          --delivery-pipeline=repointerviewer-pipeline \
          --region=asia-northeast1 \
          --source=. \
          --skaffold-file=skaffold.yaml