# generated by fastapi-codegen:
#   filename:  api.yml
#   timestamp: 2025-05-19T12:37:04+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class InterviewInterviewIdPostRequest(BaseModel):
    question_id: str
    message: str


class InterviewInterviewIdPostResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    interview_id: str
    question_id: str
    score: int = Field(ge=0, le=100)
    response: str
    # レスポンスボディのキー名を continue にするため
    continue_: bool = Field(alias="continue")
