name: Deploy Redoc to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'api.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install redoc-cli
        run: npm install -g redoc-cli

      - name: Generate Redoc HTML
        run: |
          mkdir -p out
          redoc-cli bundle api.yaml --cdn -o out/index.html
          touch out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
