name: Run Backend Tests

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 要求レベル最低version

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Create venv and Install dependencies
        run: uv sync --dev # dev グループの依存関係もインストール

      - name: Run Tests
        run: |
          export PYTHONPATH=$(pwd) # 現在のワーキングディレクトリ (backend) を PYTHONPATH に設定
          uv run pytest tests
